### ISSUE TITLE
Multi-root Workspace support

### ISSUE THREAD

**Issue by Rasmus-Bertell** [phoihos/vscode-git-commit-message-editor#1]
I have a multi-root workspace and no matter where I open the commit editor it always edits the message for the folder defined last in workspace settings.

**Comment by RasmusBertell** [comment]
Thanks, I now understand better how this works. However I still think this needs some modification in the behavior.

![multi-root workspace](https://user-images.githubusercontent.com/57398362/137263411-33b31b57-f32f-49c2-91ee-da8665a7ed44.png)

In the above image pressing the edit button next to the repository should take to the repositorys commit message instead of the selected repositorys commit message in my opinion.
